# Generated by Django 5.0.6 on 2024-11-05 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Detentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evacuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_turn', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='StopCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='StopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField()),
                ('stop_code', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('stop_time', models.IntegerField()),
                ('observation', models.TextField(null=True)),
                ('inputable', models.CharField(default=True, max_length=10)),
                ('cabin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.cabin')),
                ('cabin2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.cabin2')),
                ('event_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.eventtype')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.station')),
            ],
        ),
        migrations.CreateModel(
            name='EventStopCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_paradas.eventtype')),
            ],
            options={
                'unique_together': {('event_type', 'content_type', 'object_id')},
            },
        ),
    ]
