# Generated by Django 5.1.3 on 2024-11-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paradas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('horometer_start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_time', models.TimeField()),
                ('horometer_end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
