# Generated by Django 5.1.3 on 2024-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_paradas', '0002_operationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationtime',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
